theme: jekyll-theme-minimal
title: S Divakar Bhat
description: Graduate Research Assistant, Vision and Image Processing Lab, IIT Bombay
contact: sdivakarbhat [AT] gmail [DOT] com, sdivakarbhat [AT] iitb [DOT] ac [DOT] in
logo: https://avatars3.githubusercontent.com/u/42075133?s=400&u=9f29f0779b114e7ec7ee2038f3c2bec4533f8a4d&v=4
